---
- include: Ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- include: CentOS.yml
  when: ansible_distribution == "CentOS"

- name: Add header for IE9 compatibility
  lineinfile: "dest={{SYS_APACHE_MODS_DIR}}/ie9-compat.conf
    line='Header set X-UA-Compatible: IE=EDGE'
    create=yes"
  notify: reload apache

- name: chown home dir of apache user
  file: path={{SYS_APACHE_HOME}} state=directory owner={{SYS_APACHE_USER}} group={{SYS_APACHE_GROUP}}

- name: copy basic security file to take effect
  template: src=conf.d_security.conf.j2 dest="{{SYS_APACHE_CONF_DIR}}/security.conf" owner=root group=root mode=0444
  notify: reload apache

# OS independent config
- name: webapps dir
  file: path={{APACHE_WEBAPP_DIR}} state=directory owner=root group=root

- name: docroot dir
  file: path={{APACHE_DOCROOT}} state=directory owner=root group=root

- name: give read access to apache log dir
  file: path={{SYS_APACHE_LOG_DIR}} state=directory mode=o+xr
#- name: ensure that we did not mess up apache config
#  command: apache2ctl -t
#  changed_when: false