---
- include_vars: "{{ansible_distribution}}.yml"

- include_vars: "{{item}}"
  with_first_found:
  - "{{ansible_distribution}}-{{ansible_distribution_version}}.yml"
  - "{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml"

- include_vars: "apache-{{ SYS_APACHE_VERSION }}.yml"

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
  with_items:
  - "{{ APACHE_WEBAPP_DIR }}"
  - "{{ APACHE_DOCROOT }}"
  tags: [ apache, flesh ]

- name: give read access to apache log dir
  file:
    path: "{{ SYS_APACHE_LOG_DIR }}"
    state: directory
    mode: o+xr

- set_fact:
    _php: "{{ apache_php_packages }}"
  when: apache_enable_php

- name: Install Apache2
  package:
    name: "{{ apache_base_packages | union(apache_other_packages) | union(_php | default([]) ) }}"
    state: present
  tags: [ apache, packages, flesh ]

- include_tasks: "{{ task_file }}"
  with_items:
  - "apache_{{ ansible_distribution }}.yml"
  - "apache_base_conf.yml"
  loop_control:
    loop_var: task_file
  tags: [ apache, packages, flesh ]

- name: Install python passlib for htpasswd module
  pip: 
    name: passlib
    state: present

