---
- include_vars: "{{ansible_distribution}}.yml"

- include_vars: "{{item}}"
  with_first_found:
  - "{{ansible_distribution}}-{{ansible_distribution_version}}.yml"
  - "{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml"

- include_vars: "apache-{{ SYS_APACHE_VERSION }}.yml"

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
  with_items:
  - "{{ APACHE_WEBAPP_DIR }}"
  - "{{ APACHE_DOCROOT }}"

- name: give read access to apache log dir
  file:
    path: "{{ SYS_APACHE_LOG_DIR }}"
    state: directory
    mode: o+xr

- name: Ensure python-pip is available
  apt:
    name: "{{ item }}"
    state: present
  with_items:
  - python-pip

- name: Install python passlib for htpasswd module
  pip: 
    name: passlib
    state: present

- name: Install Apache2
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ apache_packages }}"
  tags: packages

- include_tasks: "apache_install_{{ ansible_distribution }}.yml"
- include_tasks: "apache_base_conf.yml"

