---
- include_vars: "{{ansible_distribution}}.yml"

- include_vars: "{{item}}"
  with_first_found:
  - "{{ansible_distribution}}-{{ansible_distribution_version}}.yml"
  - "{{ansible_distribution}}-{{ansible_distribution_major_version}}.yml"

- include_vars: "apache-{{ SYS_APACHE_VERSION }}.yml"

- name: create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - "{{ APACHE_WEBAPP_DIR }}"
  - "{{ APACHE_DOCROOT }}"

- include_tasks: "apache_install_{{ ansible_distribution }}.yml"

- include_tasks: "apache_base_conf.yml"

