---
- name: Install requirements
  apt: name="{{item}}" state=present
  tags: packages
  with_items:
  - python-pip

- name: install python passlib for htpasswd module
  pip: name=passlib state=present

- name: Install Apache2
  apt: name="{{item}}" state=present
  tags: packages
  with_items:
  - apache2
  - apache2-utils
  - libapache2-mod-wsgi
  - libapache2-mod-php5
  - libapache2-mod-fastcgi

- name: Install php5  state=present
  apt: name={{ item }}
  tags: packages
  with_items:
  - php5
  - php5-common
  - php5-cgi
  - php5-cli
  - php5-curl
  - php5-json
  - php5-odbc
  - php5-sqlite
  - php5-mysql
  notify: restart apache

# php caching module does not work with ubuntu1404 and owncloud8
# as php modules are global we disable caching globally
- name: Uninstall php caching module on Ubuntu1404
  apt: name={{ item }} state=absent
  with_items:
  - php5-apcu
  tags: packages
  when: SYS_APACHE_VERSION|version_compare('2.4', '==')
  notify: restart apache

- name: addapt php.ini
  lineinfile: 'dest=/etc/php5/apache2/php.ini
    regexp="^[;\s]*default_charset\s*=\s*"
    line="default_charset = \"UTF-8\""'
  notify: reload apache

- name: Enable apache modules
  apache2_module: state=present name={{item}}
  with_items:
  - authn_file
  - authz_user
  - env
  - fastcgi
  - headers
  - php5
  - proxy
  - proxy_http
  - ssl
  - rewrite
  - userdir
  - wsgi
  notify: restart apache

- name: Enable ldap apache modules
  apache2_module: state=present name={{item}}
  with_items:
  - ldap
  - authnz_ldap
  notify: restart apache
  when: APACHE_USE_LDAP

- name: no compat module on apache2.4
  apache2_module: state=present name={{item}}
  with_items:
  - access_compat
  - authz_core
  when: SYS_APACHE_VERSION|version_compare('2.4', '==')
  notify: restart apache

# requires mod_xml2enc which is n/a on Ubuntu yet
#  - proxy_html

- name: Disable default apache sites
  file: path="/etc/apache2/sites-enabled/{{item}}" state=absent
  with_items:
  - 000-default
  - 000-default.conf
  - 000-default-ssl
  - 000-default-ssl.conf
  - egroupware.conf # may be left-over from egroupware installation
  notify: reload apache

- debug: msg="APACHE_USE_HTTP is {{APACHE_USE_HTTP}}"
- debug: msg="APACHE_USE_HTTPS is {{APACHE_USE_HTTPS}}"

- set_fact: __abs_or_pres=absent
- set_fact: __abs_or_pres=present
  when: APACHE_USE_HTTP

- lineinfile: dest=/etc/apache2/ports.conf regexp='\s*[l|L]isten\s+80' line='Listen 80' state={{ __abs_or_pres }}
  notify: restart apache

- set_fact: __abs_or_pres=absent
- set_fact: __abs_or_pres=present
  when: APACHE_USE_HTTPS

- lineinfile: dest=/etc/apache2/ports.conf regexp='\s*[l|L]isten\s+443' line='Listen 443' state={{ __abs_or_pres }}
  notify: restart apache

- template: src=conf.d_name_virtual_host.conf.j2 dest={{SYS_APACHE_CONF_DIR}}/name_virtual_host.conf owner=root group=root mode=0444
  when: APACHE_USE_NAMEVIRTUALHOST
  when: SYS_APACHE_VERSION|version_compare('2.4', '<')
  notify: restart apache

- template: src=conf.d_ldap.conf.j2 dest={{SYS_APACHE_CONF_DIR}}/ldap.conf owner=root group=root mode=0444
  when: APACHE_USE_LDAP
  notify: restart apache

- name: set global server name
  template: src=fqdn.conf.j2 dest={{SYS_APACHE_CONF_DIR}}/fqdn.conf
  notify: restart apache

##################################################
# configuration of the firewall
##################################################
- set_fact: ufw_is_active=false

- name: check if firewall is enabled
  shell: LANG=C ufw status
  changed_when: false
  register: ufw_status

- set_fact: ufw_is_active=true
  when: "'Status: active' in ufw_status.stdout"

- name: open port 80
  ufw: rule=allow name=Apache
  when: ufw_is_active and APACHE_USE_HTTP

- name: open port 443
  ufw: rule=allow name="Apache Secure"
  when: ufw_is_active and APACHE_USE_HTTPS

#- name: cleanup stale vhosts.
#  shell: rm -f /etc/apache2/sites-enabled/*
#  changed_when: false



